from langchain_google_genai import GoogleGenerativeAIEmbeddings
from dotenv import load_dotenv
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

load_dotenv()

embeddings = GoogleGenerativeAIEmbeddings(
    model="gemini-embedding-2",
    task_type="SEMANTIC_SIMILARITY",
    output_dimensionality=512
)

documents = [
    "Cricket is one of the world's most popular bat-and-ball sports, played between two teams of eleven players each. Originating in England during the 16th century, the game has grown into a global phenomenon, especially in countries such as India, Australia, England, and Pakistan. Cricket is played in three major formats: Test cricket (up to five days), One Day Internationals (50 overs per side), and Twenty20 (20 overs per side). The sport is governed internationally by the International Cricket Council. Some of the greatest cricketers in history include Sachin Tendulkar, who scored a record 100 international centuries and over 34,000 international runs, and Virat Kohli, known for his exceptional batting consistency. The most prestigious cricket tournament is the Cricket World Cup, first held in 1975. Cricket combines strategy, skill, endurance, and teamwork, making it one of the most followed sports globally.",
  "Football, known as soccer in some countries, is the most popular sport in the world, with an estimated fan base of over 4 billion people. The game is played between two teams of eleven players, with the objective of scoring goals by getting the ball into the opponent's net. Modern football originated in England in the 19th century, and today it is governed by FIFA. The sport's premier international tournament is the FIFA World Cup, held every four years since 1930. Legendary footballers such as Pelé, Diego Maradona, Lionel Messi, and Cristiano Ronaldo have helped shape the sport's history. Football's simplicity, requiring only a ball and open space, has contributed significantly to its worldwide popularity. Major club competitions such as the UEFA Champions League attract hundreds of millions of viewers annually.",
  "Basketball is a fast-paced team sport that originated in the United States in the late 19th century. It was invented by Dr. James Naismith in 1891 as a way to keep athletes in shape during the winter months. The game is played between two teams of five players each, with the objective of scoring points by shooting a ball through the opponent's hoop. The National Basketball Association (NBA) is the premier professional basketball league globally, featuring some of the greatest players in history, including Michael Jordan, LeBron James, and Kobe Bryant. Basketball is known for its high-scoring games, athleticism, and strategic play. The sport has a significant following worldwide, with major international competitions such as the FIBA Basketball World Cup and the Olympic Games showcasing top talent from around the globe.",
  "Tennis is a popular racket sport that can be played individually against a single opponent (singles) or between two teams of two players each (doubles). The game originated in France in the 12th century and evolved into its modern form in England during the 19th century. Tennis is played on various surfaces, including grass, clay, and hard courts, with the four Grand Slam tournaments (Australian Open, French Open, Wimbledon, and US Open) being the most prestigious events in the sport. Legendary tennis players such as Roger Federer, Rafael Nadal, Serena Williams, and Novak Djokovic have made significant contributions to the sport's history. Tennis is known for its combination of physical endurance, strategic play, and mental toughness, making it a favorite among sports enthusiasts worldwide.",
  "Baseball is a bat-and-ball sport that originated in the United States in the 19th century. It is played between two teams of nine players each, with the objective of scoring runs by hitting a pitched ball and running around a series of bases. Major League Baseball (MLB) is the premier professional baseball league globally, featuring iconic players such as Babe Ruth, Jackie Robinson, and Derek Jeter. Baseball is known for its rich history, strategic depth, and passionate fan base. The sport's most prestigious event is the World Series, held annually to determine the champion of MLB. Baseball has a significant following in countries such as the United States, Japan, and Latin America.",
  "The Taj Mahal is one of the most famous monuments in the world and a symbol of India's rich cultural heritage. Located in Agra on the banks of the Yamuna River, it was commissioned by Mughal Emperor Shah Jahan in 1632 in memory of his beloved wife Mumtaz Mahal. Constructed primarily from white marble, the mausoleum took approximately 22 years to complete and involved around 20,000 artisans and workers. The Taj Mahal is renowned for its symmetrical architecture, intricate carvings, and beautiful gardens. In 1983, it was designated a UNESCO World Heritage Site, and in 2007 it was named one of the New Seven Wonders of the World. Millions of tourists visit the monument every year, making it one of the most visited attractions in India.",
  "Virat Kohli is widely regarded as one of the greatest batsmen in cricket history. Born on November 5, 1988, in Delhi, he first gained international recognition by captaining India to victory in the 2008 Under-19 Cricket World Cup. He made his international debut later that year and quickly established himself as a world-class batsman. Kohli has scored more than 25,000 international runs across formats and has recorded over 80 international centuries, placing him among the most prolific run-scorers ever. He captained the India national cricket team from 2017 to 2022 and led the side to numerous victories, including reaching the final of the 2021 World Test Championship. Known for his aggressive style, exceptional fitness, and remarkable consistency in run chases, Kohli has won multiple ICC awards and is considered one of the most influential figures in modern cricket. He has also been a long-time star for Royal Challengers Bengaluru in the Indian Premier League.",
  "The Indian Premier League (IPL) is a professional Twenty20 cricket league in India, established in 2008 by the Board of Control for Cricket in India (BCCI). The league features franchise teams representing various cities across India, and it has become one of the most popular and lucrative cricket leagues globally. The IPL attracts top international and domestic players, offering a platform for emerging talent to showcase their skills. The tournament is known for its high-octane matches, star-studded lineups, and massive fan following. The IPL has significantly contributed to the growth of cricket in India and has had a profound impact on the sport's global landscape.",
  "Sachin Tendulkar is widely regarded as one of the greatest cricketers of all time. Born on April 24, 1973, in Mumbai, India, he made his international debut at the age of 16 and went on to have a legendary career spanning over two decades. Tendulkar is the highest run-scorer in international cricket, with over 34,000 runs across formats, and he holds the record for the most international centuries, with 100. He played a crucial role in India's cricketing successes, including the 2011 Cricket World Cup victory. Tendulkar's batting style, characterized by impeccable technique and an array of shots, earned him the nickname 'The Little Master.' He received nu  merous accolades throughout his career, including the Bharat Ratna, India's highest civilian award. Tendulkar's influence on cricket is immense, and he continues to inspire generations of cricketers and fans worldwide.",
  "Lionel Messi is considered by many to be the greatest football player of all time. Born on June 24, 1987, in Rosario, Messi joined the youth academy of FC Barcelona at the age of 13 and made his first-team debut in 2004. During his Barcelona career, he scored 672 goals in official matches, becoming the club's all-time leading scorer. Messi has won a record eight Ballon d'Or awards, given annually to the world's best footballer. His crowning achievement came in 2022 when he captained Argentina national football team to victory in the 2022 FIFA World Cup, fulfilling a lifelong dream. Throughout his career, Messi has amassed more than 850 senior career goals and hundreds of assists, showcasing extraordinary dribbling, vision, passing, and finishing abilities. His achievements at club and international levels have cemented his legacy as one of the greatest athletes in sporting history."
]

print(f"Total documents: {len(documents)}")

# query = "Who is the greatest cricketer of all time?"
query = "Which player has played for Royal Challengers Bengaluru?"

# Embed each document individually (API limitation with batch processing)
print("Embedding documents individually...")
docs_embeddings = [embeddings.embed_query(doc) for doc in documents]

print(f"Total embeddings returned: {len(docs_embeddings)}")
query_embedding = embeddings.embed_query(query)


cosine_similarity_scores = cosine_similarity([query_embedding], docs_embeddings)[0]
cosine_similarity_scores = list(enumerate(cosine_similarity_scores))    
print("Cosine similarity scores:", sorted(cosine_similarity_scores, key=lambda x: x[1], reverse=True))

index, score = sorted(cosine_similarity_scores, key=lambda x: x[1], reverse=True)[0]
print(f"Most similar document index: {index}, Cosine similarity score: {score}")
print("Most similar document:", documents[index])